Algoritmo "MULTIPLO10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2024
Var
// Seção de Declarações das variáveis 
contador : inteiro


Inicio
contador <- 1
enquanto (contador <= 100) faca
se (contador % 10 = 0) entao
    escreval(contador," é múltiplo de 10")
senao
    escreval(contador)
fimSe
contador <- contador + 1
fimEnquanto


Fimalgoritmo