Algoritmo "matriz"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/03/2024
Var
// Seção de Declarações das variáveis 
m : vetor[1..3,1..2] de inteiro
l,c : inteiro

Inicio
para l <- 1 ate 3 faca
  para c <- 1 ate 2 faca
    leia(m[l,c])
  fimPara
fimPara


Fimalgoritmo